name: Desplegar SistemaCalificaciones en Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo de GitHub
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Compilar proyecto con Maven
        run: |
          cd SistemaCalificaciones
          mvn clean package -DskipTests

      - name: Desplegar archivo WAR en Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'calificaciones-paginita'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: 'SistemaCalificaciones/target/*.war'
