name: Desplegar SistemaCalificaciones en Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo de GitHub
        uses: actions/checkout@v4

      - name: Crear ROOT.war
        run: |
          cd SistemaCalificaciones
          jar -cvf ../ROOT.war *

      - name: Desplegar en Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'calificaciones-paginita'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: 'ROOT.war'
