name: Desplegar en Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo de GitHub
        uses: actions/checkout@v4

      - name: Desplegar archivos en Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'calificaciones-paginita'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: 'SistemaCalificaciones'
